-- MySQL Script generated by MySQL Workbench
-- Sat Jul 10 21:33:55 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------
USE `hotel` ;

-- -----------------------------------------------------
-- Table `hotel`.`lifestyle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`lifestyle` (
  `no` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(10) NOT NULL,
  `subtype` VARCHAR(10) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `info` TEXT NULL,
  `info_detail` TEXT NULL,
  `hours` TEXT NULL,
  `location` VARCHAR(45) NULL,
  `contact` VARCHAR(20) NULL,
  `wdate` TIMESTAMP NULL DEFAULT current_timestamp,
  `modify_date` TIMESTAMP NULL DEFAULT current_timestamp,
  PRIMARY KEY (`no`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`lifestyle_price`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`lifestyle_price` (
  `no` INT NOT NULL AUTO_INCREMENT,
  `price_type` VARCHAR(20) NULL,
  `price` VARCHAR(20) NULL,
  `lifestyle_no` INT NOT NULL,
  PRIMARY KEY (`no`),
  INDEX `fk_lifestyle_price_lifestyle1_idx` (`lifestyle_no` ASC) ,
  CONSTRAINT `fk_lifestyle_price_lifestyle1`
    FOREIGN KEY (`lifestyle_no`)
    REFERENCES `hotel`.`lifestyle` (`no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`lifestyle_image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`lifestyle_image` (
  `no` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `size` INT NULL,
  `lifestyle_no` INT NOT NULL,
  PRIMARY KEY (`no`),
  INDEX `fk_lifestyle_image_lifestyle1_idx` (`lifestyle_no` ASC) ,
  CONSTRAINT `fk_lifestyle_image_lifestyle1`
    FOREIGN KEY (`lifestyle_no`)
    REFERENCES `hotel`.`lifestyle` (`no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`lifestyle_facility`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`lifestyle_facility` (
  `lifeFacility_no` INT NOT NULL AUTO_INCREMENT,
  `lifeFacility_image_name` VARCHAR(45) NULL,
  `lifeFacility_image_size` INT NULL,
  `lifeFacility_title` VARCHAR(45) NULL,
  `lifeFacility_info` TEXT NULL,
  `lifestyle_no` INT NOT NULL,
  PRIMARY KEY (`lifeFacility_no`),
  INDEX `fk_lifestyle_facility_lifestyle1_idx` (`lifestyle_no` ASC) ,
  CONSTRAINT `fk_lifestyle_facility_lifestyle1`
    FOREIGN KEY (`lifestyle_no`)
    REFERENCES `hotel`.`lifestyle` (`no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
