-- MySQL Script generated by MySQL Workbench
-- Thu Jul  8 16:30:57 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotel` DEFAULT CHARACTER SET utf8 ;
USE `hotel` ;

-- -----------------------------------------------------
-- Table `hotel`.`reservation_adm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`reservation_adm` (
  `no` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `title_s` VARCHAR(100) NULL,
  `date_start` TIMESTAMP NULL,
  `date_end` TIMESTAMP NULL,
  `thum` BLOB NULL,
  `content` VARCHAR(150) NULL,
  `benefits` VARCHAR(45) NULL,
  `room_write` TIMESTAMP NULL DEFAULT current_timestamp,
  PRIMARY KEY (`no`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`reservation` (
  `no` INT NOT NULL AUTO_INCREMENT,
  `reservation_no` VARCHAR(45) NULL,
  `date_write` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `check_in` TIMESTAMP  NULL,
  `check_out` TIMESTAMP NULL,
  `room_count` INT NOT NULL DEFAULT 1,
  `count_adult` INT NULL,
  `count_elementary` INT NULL,
  `count_child` INT NULL,
  `count_baby` INT NULL,
  `count_all` INT NOT NULL,
  `promotion_name` VARCHAR(45) NULL,
  `promotion_code` INT NULL,
  `breakfast_adult` INT NULL,
  `breakfast_child` INT NULL,
  `price_product` INT NOT NULL,
  `price_service` INT NOT NULL,
  `price_bed` INT NOT NULL,
  `price_options` INT NOT NULL,
  `price_total` INT NOT NULL,
  `member_id` VARCHAR(45) NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `tel` VARCHAR(45) NOT NULL,
  `add_requests` VARCHAR(150) NULL,
  `state` VARCHAR(45) NOT NULL DEFAULT 0,
  `member1_no` INT NOT NULL,
  `reservation_adm_no` INT NOT NULL,
  `member_no` INT NOT NULL,
  `rooms_no` INT NOT NULL,
  PRIMARY KEY (`no`),
  INDEX `fk_reservation_reservation_adm1_idx` (`reservation_adm_no` ASC) ,
  INDEX `fk_reservation_member1_idx` (`member_no` ASC) ,
  INDEX `fk_reservation_rooms1_idx` (`rooms_no` ASC) ,
  CONSTRAINT `fk_reservation_reservation_adm1`
    FOREIGN KEY (`reservation_adm_no`)
    REFERENCES `hotel`.`reservation_adm` (`no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_member1`
    FOREIGN KEY (`member_no`)
    REFERENCES `hotel`.`member` (`no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_rooms1`
    FOREIGN KEY (`rooms_no`)
    REFERENCES `hotel`.`rooms` (`no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`rez_adm_room_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`rez_adm_room_type` (
  `reservation_adm_no` INT NOT NULL,
  `room_type_no` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `benefit` VARCHAR(200) NULL,
  PRIMARY KEY (`reservation_adm_no`, `room_type_no`),
  INDEX `fk_reservation_adm_has_room_type_room_type1_idx` (`room_type_no` ASC) ,
  INDEX `fk_reservation_adm_has_room_type_reservation_adm1_idx` (`reservation_adm_no` ASC) ,
  CONSTRAINT `fk_reservation_adm_has_room_type_reservation_adm1`
    FOREIGN KEY (`reservation_adm_no`)
    REFERENCES `hotel`.`reservation_adm` (`no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_adm_has_room_type_room_type1`
    FOREIGN KEY (`room_type_no`)
    REFERENCES `hotel`.`room_type` (`no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
